# Generated by Django 5.0.7 on 2024-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='defualt_profile_images/default_image.jpeg', upload_to='profile_images/'),
        ),
    ]
