# Generated by Django 5.0.7 on 2024-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='f1bb09d3-3443-404a-84e6-3f332db139ed', primary_key=True, serialize=False, unique=True),
        ),
    ]
