# Generated by Django 5.0.7 on 2024-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='81a379e5-9fed-450c-b136-e705833c6106', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='$<django.db.models.fields.CharField>_$<django.db.models.fields.CharField>', max_length=100, unique=True),
        ),
    ]
