# Generated by Django 5.0.7 on 2024-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='360b3158-2ad5-4b7b-9cb5-4a4870c81073', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='$<bound method Field.value_from_object of <django.db.models.fields.CharField>>_$<bound method Field.value_from_object of <django.db.models.fields.CharField>>', max_length=100, unique=True),
        ),
    ]
