# Generated by Django 5.0.7 on 2024-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='e785e809-61e5-458e-aa95-dc20931f853f', primary_key=True, serialize=False, unique=True),
        ),
    ]
