# Generated by Django 5.1.2 on 2025-01-26 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('assigned_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('test_scores', models.JSONField(default=dict)),
                ('exam_scores', models.JSONField(default=dict)),
                ('times_sch_opened', models.IntegerField(blank=True, null=True)),
                ('times_present', models.IntegerField(blank=True, null=True)),
                ('sports', models.IntegerField(blank=True, null=True)),
                ('gymnastics', models.IntegerField(blank=True, null=True)),
                ('handling_of_tools', models.IntegerField(blank=True, null=True)),
                ('creativity', models.IntegerField(blank=True, null=True)),
                ('mustical_skill', models.IntegerField(blank=True, null=True)),
                ('dancing_skill', models.IntegerField(blank=True, null=True)),
                ('drawing_and_painting', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
                ('affective', models.IntegerField(blank=True, null=True)),
                ('self_control', models.IntegerField(blank=True, null=True)),
                ('reliability', models.IntegerField(blank=True, null=True)),
                ('neatness', models.IntegerField(blank=True, null=True)),
                ('politeness', models.IntegerField(blank=True, null=True)),
                ('honesty', models.IntegerField(blank=True, null=True)),
                ('interpersonal', models.IntegerField(blank=True, null=True)),
                ('relationship', models.IntegerField(blank=True, null=True)),
                ('puncuality', models.IntegerField(blank=True, null=True)),
                ('team_spirit', models.IntegerField(blank=True, null=True)),
                ('reqularity', models.IntegerField(blank=True, null=True)),
                ('leadership_traits', models.IntegerField(blank=True, null=True)),
                ('class_teacher_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('principals_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject', to=settings.AUTH_USER_MODEL)),
                ('students_offering', models.ManyToManyField(blank=True, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
