# Generated by Django 5.1.2 on 2025-03-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('assigned_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('scores', models.JSONField(blank=True, default=dict, help_text="Store scores as {'Math': {'test': 40, 'exam': 60}}", null=True)),
                ('general_remarks', models.JSONField(blank=True, default=dict, help_text="Store general remarks and traits as {'politeness': 5, 'sports': 4}", null=True)),
                ('comments', models.JSONField(blank=True, default=dict, help_text="Store teacher and principal comments as {'Principals_Comment': 'Very Good Student', 'Teachers_Remark':'Very Focused Student', 'Resumption_Date':'25TH OF January 2025'}.", null=True)),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_results', to='academics.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject', to=settings.AUTH_USER_MODEL)),
                ('students_offering', models.ManyToManyField(blank=True, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
