# Generated by Django 5.0.7 on 2024-07-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sujects', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='uploadlist',
            name='name',
            field=models.CharField(blank=True, default='Upload_List#281e4583-4ef4-493b-9899-e7779154bd65', max_length=60, unique=True),
        ),
    ]
