# Generated by Django 5.1.2 on 2025-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentresult_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='affective',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='class_teacher_comments',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='dancing_skill',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='drawing_and_painting',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_scores',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='gymnastics',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='handling_of_tools',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='honesty',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='interpersonal',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='leadership_traits',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='mustical_skill',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='neatness',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='politeness',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='principals_comments',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='puncuality',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='reliability',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='reqularity',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='self_control',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='team_spirit',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test_scores',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='times_present',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='times_sch_opened',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='comments',
            field=models.JSONField(blank=True, help_text="Store teacher and principal comments as {'Principals_Comment': 'Very Good Student', 'Teachers_Remark':'Very Focused Student', 'Resumption_Date':'25TH OF January 2025'}.", null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='general_remarks',
            field=models.JSONField(blank=True, default=dict, help_text="Store general remarks and traits as {'politeness': 5, 'sports': 4}", null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='scores',
            field=models.JSONField(blank=True, default=dict, help_text="Store scores as {'Math': {'test': 40, 'exam': 60}}", null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='term',
            field=models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=10),
        ),
    ]
