# Generated by Django 5.1.2 on 2025-01-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_studentresult_affective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_results', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text="Store teacher and principal comments as {'Principals_Comment': 'Very Good Student', 'Teachers_Remark':'Very Focused Student', 'Resumption_Date':'25TH OF January 2025'}.", null=True),
        ),
    ]
