# Generated by Django 5.0.7 on 2024-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_result_name_alter_uploadlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlist',
            name='name',
            field=models.CharField(blank=True, default='Upload_List#e8512d13-0c82-4f40-aae9-15f62fcaa8bd', max_length=60, unique=True),
        ),
    ]
