# Generated by Django 5.0.7 on 2024-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_uploadlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlist',
            name='name',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
