# Generated by Django 5.0.7 on 2024-07-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_uploadlist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AlterField(
            model_name='result',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='result',
            name='assigned_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students_offering',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='students_offering',
            field=models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
