# Generated by Django 5.0.7 on 2024-07-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_classroom_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlist',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploadlists', to='academics.classroom'),
        ),
    ]
